# fly.toml file generated for coderd on 2022-04-25T14:13:46-05:00

app = "coderd"

kill_signal = "SIGINT"
kill_timeout = 60
processes = []

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/go"]

  [build.args]
    BP_GO_TARGETS = "./cmd/coder"
    BP_GO_BUILD_FLAGS = "-tags=embed"

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true
  entrypoint = ["/cnb/process/coder"]
  cmd = [
    "server",
    "--access-url", "https://coderd.fly.io",
    "--address", "0.0.0.0:8080"
  ]

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []

  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
